//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.09 at 06:22:45 PM ICT 
//


package com.eventmap.fluent.domain.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eventmap.fluent.domain.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RulesCategoryRuleMessageSuggestion_QNAME = new QName("", "suggestion");
    private final static QName _RulesCategoryRuleExampleMarker_QNAME = new QName("", "marker");
    private final static QName _RulesCategoryRulePatternMarkerTokenException_QNAME = new QName("", "exception");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eventmap.fluent.domain.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rules }
     * 
     */
    public Rules createRules() {
        return new Rules();
    }

    /**
     * Create an instance of {@link Rules.Category }
     * 
     */
    public Rules.Category createRulesCategory() {
        return new Rules.Category();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule }
     * 
     */
    public Rules.Category.Rule createRulesCategoryRule() {
        return new Rules.Category.Rule();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Pattern }
     * 
     */
    public Rules.Category.Rule.Pattern createRulesCategoryRulePattern() {
        return new Rules.Category.Rule.Pattern();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Pattern.Marker }
     * 
     */
    public Rules.Category.Rule.Pattern.Marker createRulesCategoryRulePatternMarker() {
        return new Rules.Category.Rule.Pattern.Marker();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Pattern.Marker.Token }
     * 
     */
    public Rules.Category.Rule.Pattern.Marker.Token createRulesCategoryRulePatternMarkerToken() {
        return new Rules.Category.Rule.Pattern.Marker.Token();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Message }
     * 
     */
    public Rules.Category.Rule.Message createRulesCategoryRuleMessage() {
        return new Rules.Category.Rule.Message();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Example }
     * 
     */
    public Rules.Category.Rule.Example createRulesCategoryRuleExample() {
        return new Rules.Category.Rule.Example();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Pattern.Token }
     * 
     */
    public Rules.Category.Rule.Pattern.Token createRulesCategoryRulePatternToken() {
        return new Rules.Category.Rule.Pattern.Token();
    }

    /**
     * Create an instance of {@link Rules.Category.Rule.Pattern.Marker.Token.Exception }
     * 
     */
    public Rules.Category.Rule.Pattern.Marker.Token.Exception createRulesCategoryRulePatternMarkerTokenException() {
        return new Rules.Category.Rule.Pattern.Marker.Token.Exception();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "suggestion", scope = Rules.Category.Rule.Message.class)
    public JAXBElement<String> createRulesCategoryRuleMessageSuggestion(String value) {
        return new JAXBElement<String>(_RulesCategoryRuleMessageSuggestion_QNAME, String.class, Rules.Category.Rule.Message.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "marker", scope = Rules.Category.Rule.Example.class)
    public JAXBElement<String> createRulesCategoryRuleExampleMarker(String value) {
        return new JAXBElement<String>(_RulesCategoryRuleExampleMarker_QNAME, String.class, Rules.Category.Rule.Example.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Rules.Category.Rule.Pattern.Marker.Token.Exception }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "exception", scope = Rules.Category.Rule.Pattern.Marker.Token.class)
    public JAXBElement<Rules.Category.Rule.Pattern.Marker.Token.Exception> createRulesCategoryRulePatternMarkerTokenException(Rules.Category.Rule.Pattern.Marker.Token.Exception value) {
        return new JAXBElement<Rules.Category.Rule.Pattern.Marker.Token.Exception>(_RulesCategoryRulePatternMarkerTokenException_QNAME, Rules.Category.Rule.Pattern.Marker.Token.Exception.class, Rules.Category.Rule.Pattern.Marker.Token.class, value);
    }

}
